using UnityEngine;

[CreateAssetMenu(fileName = "CommercialUnit", menuName = "Unit Data/Commercial", order = 2)]
public class CommercialUnit : UnitData
{
    // Add commercial unit-specific properties and methods here
    // money generated by commercial unit
    public int revenue { get; set; }
    // rent charged to resident
    public int rent { get; set; }
    // cost to purchase unit
    public int cost { get; set; }
    // cost to maintain unit
    public int maintenance { get; set; }
    // cost to repair unit
    public int repair { get; set; }
    // cost to upgrade unit
    public int upgrade { get; set; }
    // cost to demolish unit
    public int demolish { get; set; }
    // cost to evict resident
    public int eviction { get; set; }
    // cost to sell unit
    public int sale { get; set; }
    // cost to buyout unit
    public int buyout { get; set; }
    // cost to build unit
    public int build { get; set; }
    // cost to open unit
    public int open { get; set; }
    // cost to close unit
    public int close { get; set; }


    // add resident assigned to commerical unit
    public ResidentData resident { get; set; }
    // set if unit is occupied

    public bool isOccupied { get; set; }

    // set if unit is open
    public bool isOpen { get; set; }

    
    public CommercialUnit()
    {
        isOccupied = false;
        isOpen = false;
    }

    public void Open()
    {
        isOpen = true;
    }

    public void Close()
    {
        isOpen = false;
    }

    public void AssignResident(ResidentData resident)
    {
        this.resident = resident;
        isOccupied = true;
    }

    public void UnassignResident()
    {
        resident = null;
        isOccupied = false;
    }

    public void Sell()
    {
        UnassignResident();
        Close();
    }

    public void Evict()
    {
        UnassignResident();
    }


    public void UpgradeUnit()
    {
        // upgrade unit
        
        

    }

}
